### ISSUE TITLE
No BOMB method in docker image

### ISSUE THREAD

**Issue by alexnest-ua** [porthole-ascend-cinnamon/mhddos_proxy#36] opened 2022-03-24 13:08 UTC
runner.py: error: argument --http-methods: invalid choice: 'BOMB' (choose from 'APACHE', 'SLOW', 'PPS', 'CFBUAM', 'NULL', 'AVB', 'POST', 'BOT', 'COOKIE', 'BYPASS', 'GSB', 'DYN', 'OVH', 'EVEN', 'HEAD', 'XMLRPC', 'STRESS', 'GET', 'CFB', 'DOWNLOADER')

But in origin MHDDoS it includes: https://github.com/MHProDev/MHDDoS#features-and-methods

**Comment by porthole-ascend-cinnamon** [comment] 2022-03-24 16:32
That's right, BOMB method is not included. Feel free to provide a PR for it's support. The issue is duplicate of #18, please at least read the existing issues before opening a new one - there are not so much of them.

**Closed by porthole-ascend-cinnamon** 2022-03-24 16:32 UTC
