### ISSUE TITLE
Add support for linux/arm64/v8

### ISSUE THREAD

**Issue by NikDevx** [porthole-ascend-cinnamon/mhddos_proxy#33] opened 2022-03-23 16:04 UTC
Hello

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error

**Comment by porthole-ascend-cinnamon** [comment] 2022-03-23 16:31
Duplicate of #27

**Closed by porthole-ascend-cinnamon** 2022-03-23 16:31 UTC
