### ISSUE TITLE
standard_init_linux.go:228: exec user process caused: no such file or directory

### ISSUE THREAD

**Issue by C0ntr07** [porthole-ascend-cinnamon/mhddos_proxy#89] opened 2022-04-19 11:36 UTC
Have been running mhddos for a couple of weeks. Just got this message on a new machine I was going to add, 

```
~/itarmy $ sudo docker run -it --rm --pull always ghcr.io/porthole-ascend-cinnamon/mhddos_proxy -t 2000 --itarmy --debug
latest: Pulling from porthole-ascend-cinnamon/mhddos_proxy
Digest: sha256:89d79ddb1ca8cf83529f525eaeb24953c1eaa36f522053ac07e824cef6494692
Status: Image is up to date for ghcr.io/porthole-ascend-cinnamon/mhddos_proxy:latest
standard_init_linux.go:228: exec user process caused: no such file or directory
```

**Comment by porthole-ascend-cinnamon** [comment] 2022-04-19 16:17
anything unusual or different about this particular machine compared to working ones?

**Comment by porthole-ascend-cinnamon** [comment] 2022-04-23 16:20
May be fixed in the latest versions, if it was caused by wrong line separators in one of the files.

**Closed by porthole-ascend-cinnamon** 2022-04-23 16:20 UTC

**Comment by C0ntr07** [comment] 2022-04-23 17:18
Thank you.
