### ISSUE TITLE
Consider forking MHDDoS and PyProxy

### ISSUE THREAD

**Issue by alexnest-ua** [porthole-ascend-cinnamon/mhddos_proxy#24] opened 2022-03-20 17:21 UTC
Traceback (most recent call last):
  File "runner.py", line 12, in <module>
    from MHDDoS.start import ProxyManager, logger
  File "/home/azureuser/mhddos_proxy/MHDDoS/start.py", line 27, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
  File "/usr/local/lib/python3.8/dist-packages/PyRoxy/__init__.py", line 13, in <module>
    from PyRoxy import GeoIP, Tools
  File "/usr/local/lib/python3.8/dist-packages/PyRoxy/Tools/__init__.py", line 18
    rand_char: Callable[[int], chr] = lambda length=16: chr(Random.rand_int(0, 1000)) for _ in range(length)
                                                                                      ^
SyntaxError: invalid syntax

I recommend the author to download the last stable version of MHDDoS and MHDDoS/PyProxy to your repositary to avoid such issues

**Comment by flunk-barrels** [comment] 2022-03-22 03:23
How can I repro this?

**Comment by porthole-ascend-cinnamon** [comment] 2022-03-22 10:03
@flunk-barrels It's fixed in the PyProxy. The issue is open as a suggestion to fork dependencies here.

**Comment by porthole-ascend-cinnamon** [comment] 2022-03-24 08:08
Forking in progress

**Closed by porthole-ascend-cinnamon** 2022-03-24 08:08 UTC
Labels: enhancement
